#ifndef SRC_KENNZEICHEN_H
#define SRC_KENNZEICHEN_H

#include <Arduino.h>

// Kennzeichen-Datenstruktur
struct Kennzeichen {
  const char* kuerzel;    // z.B. "M", "HH", "B"
  const char* stadt;      // z.B. "Muenchen", "Hamburg", "Berlin"
};

// Deutsche Kfz-Kennzeichen (haeufige und interessante)
const Kennzeichen KENNZEICHEN[] = {
  // Grossstaedte
  {"B",    "Berlin"},
  {"HH",   "Hamburg"},
  {"M",    "Muenchen"},
  {"K",    "Koeln"},
  {"F",    "Frankfurt"},
  {"S",    "Stuttgart"},
  {"D",    "Duesseldorf"},
  {"DO",   "Dortmund"},
  {"E",    "Essen"},
  {"L",    "Leipzig"},
  {"HB",   "Bremen"},
  {"DD",   "Dresden"},
  {"H",    "Hannover"},
  {"N",    "Nuernberg"},
  {"DU",   "Duisburg"},
  {"BO",   "Bochum"},
  {"W",    "Wuppertal"},
  {"BI",   "Bielefeld"},
  {"BN",   "Bonn"},
  {"MS",   "Muenster"},
  {"KA",   "Karlsruhe"},
  {"MA",   "Mannheim"},
  {"A",    "Augsburg"},
  {"WI",   "Wiesbaden"},
  {"MG",   "Moenchengladbach"},
  {"GE",   "Gelsenkirchen"},
  {"AC",   "Aachen"},
  {"BS",   "Braunschweig"},
  {"KI",   "Kiel"},
  {"C",    "Chemnitz"},
  {"HL",   "Luebeck"},
  {"MD",   "Magdeburg"},
  {"FR",   "Freiburg"},
  {"KS",   "Kassel"},
  {"OB",   "Oberhausen"},
  {"HA",   "Hagen"},
  {"HRO",  "Rostock"},
  {"EF",   "Erfurt"},
  {"MZ",   "Mainz"},
  {"SB",   "Saarbruecken"},
  {"OS",   "Osnabrueck"},
  {"OL",   "Oldenburg"},
  {"PB",   "Paderborn"},
  {"HD",   "Heidelberg"},
  {"DA",   "Darmstadt"},
  {"RE",   "Recklinghausen"},
  {"WOB",  "Wolfsburg"},
  {"R",    "Regensburg"},
  {"IN",   "Ingolstadt"},
  {"UL",   "Ulm"},
  {"HN",   "Heilbronn"},
  {"PF",   "Pforzheim"},
  {"OF",   "Offenbach"},
  {"P",    "Potsdam"},

  // Bekannte Regionen/Kreise
  {"FFB",  "Fuerstenfeldbruck"},
  {"EBE",  "Ebersberg"},
  {"STA",  "Starnberg"},
  {"LL",   "Landsberg/Lech"},
  {"GAP",  "Garmisch-Partenk."},
  {"RO",   "Rosenheim"},
  {"TS",   "Traunstein"},
  {"BGL",  "Berchtesgaden"},
  {"PA",   "Passau"},
  {"DEG",  "Deggendorf"},
  {"LA",   "Landshut"},
  {"KEH",  "Kelheim"},
  {"WUE",  "Wuerzburg"},
  {"SW",   "Schweinfurt"},
  {"BA",   "Bamberg"},
  {"CO",   "Coburg"},
  {"BT",   "Bayreuth"},
  {"HO",   "Hof"},
  {"FO",   "Forchheim"},
  {"ER",   "Erlangen"},
  {"AN",   "Ansbach"},
  {"NEA",  "Neustadt/Aisch"},
  {"FU",   "Fuerth"},

  // Weitere interessante
  {"SY",   "Sylt"},
  {"NF",   "Nordfriesland"},
  {"FL",   "Flensburg"},
  {"SL",   "Schleswig"},
  {"RD",   "Rendsburg"},
  {"NMS",  "Neumuenster"},
  {"PI",   "Pinneberg"},
  {"SE",   "Segeberg"},
  {"OD",   "Stormarn"},
  {"RZ",   "Herzogtum Lauenb."},
  {"LG",   "Lueneburg"},
  {"CE",   "Celle"},
  {"PE",   "Peine"},
  {"GF",   "Gifhorn"},
  {"WL",   "Harburg"},
  {"HI",   "Hildesheim"},
  {"NI",   "Nienburg"},
  {"HOL",  "Holzminden"},
  {"GS",   "Goslar"},
  {"WF",   "Wolfenbuettel"},
  {"SZ",   "Salzgitter"},
  {"HE",   "Helmstedt"},
  {"BOR",  "Borken"},
  {"COE",  "Coesfeld"},
  {"ST",   "Steinfurt"},
  {"WAF",  "Warendorf"},
  {"GT",   "Guetersloh"},
  {"HF",   "Herford"},
  {"MI",   "Minden"},
  {"LIP",  "Lippe"},
  {"HX",   "Hoexter"},
  {"SO",   "Soest"},
  {"UN",   "Unna"},
  {"HSK",  "Hochsauerlandkr."},
  {"SI",   "Siegen"},
  {"MK",   "Maerkischer Kr."},
  {"EN",   "Ennepe-Ruhr"},
  {"ME",   "Mettmann"},
  {"NE",   "Neuss"},
  {"KR",   "Krefeld"},
  {"VIE",  "Viersen"},
  {"HS",   "Heinsberg"},
  {"DN",   "Dueren"},
  {"EU",   "Euskirchen"},
  {"SU",   "Siegburg"},
  {"GM",   "Gummersbach"},
  {"GL",   "Bergisch Gladbach"},
  {"LEV",  "Leverkusen"},
  {"RS",   "Remscheid"},
  {"SG",   "Solingen"},
  {"KO",   "Koblenz"},
  {"MYK",  "Mayen-Koblenz"},
  {"AW",   "Ahrweiler"},
  {"NR",   "Neuwied"},
  {"WW",   "Westerwald"},
  {"AK",   "Altenkirchen"},
  {"TR",   "Trier"},
  {"BIT",  "Bitburg"},
  {"DAU",  "Daun"},
  {"WIL",  "Wittlich"},
  {"KH",   "Bad Kreuznach"},
  {"BIN",  "Bingen"},
  {"AZ",   "Alzey"},
  {"WO",   "Worms"},
  {"SP",   "Speyer"},
  {"LU",   "Ludwigshafen"},
  {"FT",   "Frankenthal"},
  {"NW",   "Neustadt/Weinstr."},
  {"KL",   "Kaiserslautern"},
  {"PS",   "Pirmasens"},
  {"ZW",   "Zweibruecken"},
  {"HOM",  "Homburg"},
  {"NK",   "Neunkirchen"},
  {"SLS",  "Saarlouis"},
  {"MZG",  "Merzig"},
  {"WND",  "St. Wendel"},
  {"GG",   "Gross-Gerau"},
  {"HP",   "Bergstrasse"},
  {"ERB",  "Erbach"},
  {"MR",   "Marburg"},
  {"LDK",  "Lahn-Dill-Kreis"},
  {"FB",   "Friedberg"},
  {"HU",   "Hanau"},
  {"MTK",  "Main-Taunus"},
  {"LM",   "Limburg"},
  {"VB",   "Vogelsberg"},
  {"FD",   "Fulda"},
  {"HEF",  "Hersfeld"},
  {"KB",   "Korbach"},
  {"ESW",  "Eschwege"},
  {"EM",   "Emmendingen"},
  {"VS",   "Villingen-Schwenn."},
  {"TUT",  "Tuttlingen"},
  {"RW",   "Rottweil"},
  {"BL",   "Balingen"},
  {"RT",   "Reutlingen"},
  {"TUE",  "Tuebingen"},
  {"ES",   "Esslingen"},
  {"BB",   "Boeblingen"},
  {"CW",   "Calw"},
  {"LB",   "Ludwigsburg"},
  {"WN",   "Waiblingen"},
  {"GP",   "Goeppingen"},
  {"AA",   "Aalen"},
  {"SHA",  "Schwaebisch Hall"},
  {"KUE",  "Kuenzelsau"},
  {"TBB",  "Tauberbischofsheim"},
  {"MOS",  "Neckar-Odenwald"},
  {"OG",   "Offenburg"},
  {"RA",   "Rastatt"},
  {"BAD",  "Baden-Baden"},
  {"FDS",  "Freudenstadt"},
  {"BC",   "Biberach"},
  {"SIG",  "Sigmaringen"},
  {"RV",   "Ravensburg"},
  {"FN",   "Friedrichshafen"},
  {"KN",   "Konstanz"},
  {"WT",   "Waldshut"},
  {"LOE",  "Loerrach"},
  {"MM",   "Memmingen"},
  {"OA",   "Oberallgaeu"},
  {"OAL",  "Ostallgaeu"},
  {"KF",   "Kaufbeuren"},
  {"NU",   "Neu-Ulm"},
  {"GZ",   "Guenzburg"},
  {"DLG",  "Dillingen"},
  {"DON",  "Donauwoerth"},
  {"AIC",  "Aichach"},
  {"ND",   "Neuburg-Schrobenh."},
  {"EI",   "Eichstaett"},
  {"WUG",  "Weissenburg"},
  {"RH",   "Roth"},
  {"SC",   "Schwabach"},
  {"LAU",  "Lauf/Pegnitz"},
  {"AS",   "Amberg-Sulzbach"},
  {"AM",   "Amberg"},
  {"NEW",  "Neustadt/Waldnaab"},
  {"WEN",  "Weiden"},
  {"TIR",  "Tirschenreuth"},
  {"CHA",  "Cham"},
  {"SAD",  "Schwandorf"},
  {"REG",  "Regen"},
  {"FRG",  "Freyung"},
  {"SR",   "Straubing"},
  {"DGF",  "Dingolfing"},
  {"PAN",  "Pfarrkirchen"},
  {"ED",   "Erding"},
  {"MUE",  "Muehldorf"},
  {"AÖ",   "Altoetting"},
  {"LF",   "Laufen"},
  {"MB",   "Miesbach"},
  {"TÖL",  "Bad Toelz"},
  {"WM",   "Weilheim"},
  {"SOG",  "Schongau"},
  {"OAL",  "Ostallgaeu"},
  {"ERH",  "Erlangen-Hoechst."},
  {"KC",   "Kronach"},
  {"KU",   "Kulmbach"},
  {"WUN",  "Wunsiedel"},
  {"LIF",  "Lichtenfels"},
  {"HAS",  "Hassberge"},
  {"NES",  "Rhoen-Grabfeld"},
  {"KG",   "Bad Kissingen"},
  {"MSP",  "Main-Spessart"},
  {"AB",   "Aschaffenburg"},
  {"MIL",  "Miltenberg"},
  {"KT",   "Kitzingen"},

  // Ostdeutschland
  {"SN",   "Schwerin"},
  {"NB",   "Neubrandenburg"},
  {"HGW",  "Greifswald"},
  {"HST",  "Stralsund"},
  {"RUE",  "Ruegen"},
  {"DBR",  "Bad Doberan"},
  {"GUE",  "Guestrow"},
  {"PCH",  "Parchim"},
  {"LWL",  "Ludwigslust"},
  {"HWI",  "Wismar"},
  {"MUE",  "Mueritz"},
  {"DM",   "Demmin"},
  {"UER",  "Uecker-Randow"},
  {"BZ",   "Bautzen"},
  {"GR",   "Goerlitz"},
  {"Z",    "Zwickau"},
  {"V",    "Vogtlandkreis"},
  {"PIR",  "Pirna"},
  {"FG",   "Freiberg"},
  {"MEI",  "Meissen"},
  {"TDO",  "Torgau"},
  {"DZ",   "Delitzsch"},
  {"WB",   "Wittenberg"},
  {"DE",   "Dessau"},
  {"ABI",  "Anhalt-Bitterfeld"},
  {"BLK",  "Burgenlandkreis"},
  {"MSH",  "Mansfeld-Suedharz"},
  {"HZ",   "Harz"},
  {"SAW",  "Salzwedel"},
  {"SDL",  "Stendal"},
  {"JL",   "Jerichower Land"},
  {"BK",   "Boerde"},
  {"SLK",  "Salzlandkreis"},
  {"J",    "Jena"},
  {"G",    "Gera"},
  {"SHL",  "Suhl"},
  {"GTH",  "Gotha"},
  {"AP",   "Weimar"},
  {"IK",   "Ilm-Kreis"},
  {"SOK",  "Saale-Orla"},
  {"SLF",  "Saalfeld"},
  {"SON",  "Sonneberg"},
  {"HBN",  "Hildburghausen"},
  {"SM",   "Schmalkalden"},
  {"WAK",  "Wartburgkreis"},
  {"EA",   "Eisenach"},
  {"UH",   "Unstrut-Hainich"},
  {"KYF",  "Kyffhaeuserkreis"},
  {"NDH",  "Nordhausen"},
  {"EIC",  "Eichsfeld"},
  {"PR",   "Prignitz"},
  {"OPR",  "Ostprignitz-Ruppin"},
  {"OHV",  "Oberhavel"},
  {"UM",   "Uckermark"},
  {"BAR",  "Barnim"},
  {"MOL",  "Maerkisch-Oderland"},
  {"LOS",  "Oder-Spree"},
  {"FF",   "Frankfurt/Oder"},
  {"CB",   "Cottbus"},
  {"SPN",  "Spree-Neisse"},
  {"OSL",  "Oberspreewald"},
  {"EE",   "Elbe-Elster"},
  {"TF",   "Teltow-Flaeming"},
  {"PM",   "Potsdam-Mittelmark"},
  {"HVL",  "Havelland"},
  {"BRB",  "Brandenburg/Havel"},
  {"LDS",  "Dahme-Spreewald"},
};

const int KENNZEICHEN_COUNT = sizeof(KENNZEICHEN) / sizeof(Kennzeichen);

// Konfusionsstaedte - echte deutsche Staedte OHNE eigenes Kennzeichen
// Diese werden als falsche Antworten verwendet, um das Quiz schwieriger zu machen
const char* KONFUSIONS_STAEDTE[] = {
  // A
  "Ahlen", "Albstadt", "Alsdorf", "Altenburg", "Arnsberg",
  // B
  "Bad Homburg", "Bad Oeynhausen", "Bad Salzuflen", "Backnang", "Balingen",
  "Bergheim", "Bergkamen", "Biberach", "Bietigheim", "Bingen", "Blomberg",
  "Bocholt", "Bottrop", "Bruhl", "Buende", "Burgdorf",
  // C
  "Castrop-Rauxel", "Cloppenburg",
  // D
  "Detmold", "Dinslaken", "Dormagen", "Dorsten", "Dreieich", "Dueren",
  // E
  "Eisenhuettenstadt", "Elmshorn", "Emden", "Emmerich", "Erftstadt",
  "Erkrath", "Eschborn", "Euskirchen", "Ettlingen",
  // F
  "Filderstadt", "Frechen", "Freising", "Friedberg", "Friedrichsdorf",
  // G
  "Garbsen", "Gerlingen", "Germering", "Gevelsberg", "Gladbeck",
  "Goch", "Goettingen", "Greiz", "Gronau", "Guetersloh",
  // H
  "Haan", "Haltern", "Hameln", "Hamm", "Hanau", "Hattersheim",
  "Hattingen", "Hennef", "Herdecke", "Herford", "Herne", "Herten",
  "Herzogenrath", "Hilden", "Hockenheim", "Hofheim", "Hoyerswerda", "Huerth",
  // I
  "Ibbenburen", "Idstein", "Iserlohn", "Itzehoe",
  // J
  "Juelich",
  // K
  "Kaarst", "Kamen", "Kamp-Lintfort", "Kempen", "Kerpen", "Ketsch",
  "Kirchheim", "Kleve", "Koenigswinter", "Kornwestheim", "Kreuztal",
  // L
  "Lage", "Lampertheim", "Langen", "Langenfeld", "Langenhagen",
  "Leichlingen", "Leinfelden", "Lemgo", "Lennestadt", "Leonberg",
  "Leverkusen", "Limbach", "Lindau", "Lingen", "Lippstadt", "Loerrach",
  "Lohmar", "Lohne", "Loehne", "Luedenscheid", "Luenen",
  // M
  "Maintal", "Marburg", "Marl", "Mechernich", "Meckenheim", "Meerbusch",
  "Meinerzhagen", "Melle", "Menden", "Meschede", "Mettmann", "Minden",
  "Moers", "Monheim", "Mörfelden", "Muehlacker", "Muehlheim", "Muelheim",
  // N
  "Neckarsulm", "Nettetal", "Neukirchen", "Neumarkt", "Neunkirchen",
  "Neuruppin", "Neuwied", "Niederkassel", "Norden", "Nordhorn", "Norderstedt",
  // O
  "Oberkirch", "Obertshausen", "Ochtrup", "Oelde", "Oer-Erkenschwick",
  "Offenbach", "Olpe", "Opladen", "Oranienburg",
  // P
  "Papenburg", "Petershagen", "Plauen", "Plettenberg", "Porta Westfalica",
  "Pulheim", "Puettlingen",
  // R
  "Radevormwald", "Radolfzell", "Ratingen", "Recklinghausen", "Rees",
  "Rheda", "Rheinbach", "Rheinberg", "Rheinfelden", "Riesa", "Rodgau",
  "Roedinghausen", "Roesrath", "Ronnenberg", "Rotenburg",
  // S
  "Saalfeld", "Sankt Augustin", "Sassnitz", "Schifferstadt", "Schloß Holte",
  "Schmallenberg", "Schorndorf", "Schwalmstadt", "Schwelm", "Schwerte",
  "Seelze", "Senden", "Sendenhorst", "Siegburg", "Sindelfingen", "Singen",
  "Soest", "Springe", "Sprockhövel", "Stadtlohn", "Steinfurt", "Stolberg",
  "Strausberg", "Sundern",
  // T
  "Taunusstein", "Toenisvorst", "Troisdorf", "Tuebingen",
  // U
  "Uelzen", "Uetersen", "Unna",
  // V
  "Vaihingen", "Verl", "Viernheim", "Voerde", "Vreden",
  // W
  "Waiblingen", "Waldbroel", "Wallenhorst", "Waltrop", "Wandlitz",
  "Warburg", "Warendorf", "Warstein", "Wedel", "Weimar", "Weinheim",
  "Weiterstadt", "Welzheim", "Werdohl", "Werl", "Wermelskirchen",
  "Wernigerode", "Wertheim", "Wesel", "Wesseling", "Wetter", "Wetzlar",
  "Wiesloch", "Willich", "Wilnsdorf", "Winnenden", "Winsen", "Witten",
  "Wittlich", "Wuelfrath", "Wuerselen", "Wunstorf",
  // X, Y, Z
  "Xanten", "Zirndorf", "Zittau", "Zweibruecken", "Zwickau"
};

const int KONFUSION_COUNT = sizeof(KONFUSIONS_STAEDTE) / sizeof(char*);

// Fake-Kennzeichen - sehen plausibel aus, existieren aber NICHT!
// Werden als falsche Antworten verwendet
const char* FAKE_KENNZEICHEN[] = {
  // A
  "AA", "AB", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AL", "AO", "AP", "AQ", "AR", "AT", "AU", "AV", "AX", "AY",
  // B
  "BA", "BC", "BD", "BE", "BF", "BG", "BJ", "BM", "BP", "BQ", "BU", "BV", "BW", "BX", "BY", "BZ",
  // C
  "CA", "CB", "CC", "CD", "CF", "CG", "CI", "CJ", "CK", "CL", "CM", "CN", "CP", "CQ", "CR", "CS", "CT", "CU", "CV", "CX", "CY", "CZ",
  // D
  "DA", "DB", "DC", "DF", "DH", "DI", "DJ", "DK", "DL", "DM", "DN", "DP", "DQ", "DR", "DS", "DT", "DV", "DW", "DX", "DY",
  // E
  "EA", "EB", "EC", "ED", "EG", "EH", "EJ", "EK", "EL", "EN", "EO", "EP", "EQ", "ET", "EV", "EW", "EX", "EY", "EZ",
  // F
  "FA", "FB", "FC", "FE", "FF", "FH", "FI", "FJ", "FK", "FL", "FM", "FP", "FQ", "FS", "FV", "FW", "FX", "FY", "FZ",
  // G
  "GA", "GB", "GC", "GD", "GH", "GI", "GJ", "GK", "GL", "GM", "GN", "GO", "GP", "GQ", "GT", "GU", "GV", "GW", "GX", "GY",
  // H
  "HC", "HD", "HE", "HF", "HG", "HJ", "HK", "HL", "HM", "HN", "HP", "HQ", "HR", "HS", "HT", "HU", "HV", "HW", "HX", "HY",
  // I
  "IA", "IB", "IC", "ID", "IE", "IF", "IG", "IH", "II", "IJ", "IL", "IM", "IO", "IP", "IQ", "IR", "IS", "IT", "IU", "IV", "IW", "IX", "IY", "IZ",
  // J
  "JA", "JB", "JC", "JD", "JE", "JF", "JG", "JH", "JI", "JJ", "JK", "JM", "JN", "JO", "JP", "JQ", "JR", "JS", "JT", "JU", "JV", "JW", "JX", "JY", "JZ",
  // K
  "KB", "KC", "KD", "KE", "KF", "KJ", "KK", "KL", "KM", "KN", "KP", "KQ", "KR", "KT", "KV", "KW", "KX", "KY", "KZ",
  // L
  "LA", "LB", "LC", "LE", "LH", "LJ", "LK", "LL", "LN", "LO", "LP", "LQ", "LR", "LS", "LT", "LU", "LV", "LX", "LY", "LZ",
  // M
  "MC", "ME", "MF", "MH", "MI", "MJ", "ML", "MM", "MN", "MO", "MP", "MQ", "MT", "MU", "MV", "MW", "MX", "MY",
  // N
  "NA", "NC", "ND", "NE", "NG", "NH", "NJ", "NK", "NL", "NN", "NO", "NP", "NQ", "NS", "NT", "NU", "NV", "NX", "NY", "NZ",
  // O
  "OA", "OC", "OD", "OE", "OF", "OG", "OH", "OI", "OJ", "OK", "OM", "ON", "OO", "OP", "OQ", "OR", "OS", "OT", "OU", "OV", "OW", "OX", "OY", "OZ",
  // P
  "PB", "PC", "PD", "PG", "PH", "PJ", "PK", "PL", "PM", "PN", "PO", "PP", "PQ", "PT", "PU", "PV", "PW", "PX", "PY", "PZ",
  // R
  "RA", "RB", "RC", "RF", "RG", "RI", "RJ", "RK", "RL", "RM", "RN", "RP", "RQ", "RR", "RS", "RT", "RU", "RX", "RY",
  // S
  "SA", "SC", "SD", "SE", "SF", "SH", "SI", "SJ", "SK", "SM", "SN", "SO", "SP", "SQ", "SR", "SS", "ST", "SU", "SV", "SW", "SX", "SY",
  // T
  "TA", "TB", "TC", "TD", "TE", "TG", "TH", "TI", "TJ", "TK", "TL", "TM", "TN", "TO", "TP", "TQ", "TR", "TT", "TU", "TV", "TW", "TX", "TY", "TZ",
  // U
  "UA", "UB", "UC", "UD", "UE", "UF", "UG", "UI", "UJ", "UK", "UO", "UP", "UQ", "UR", "US", "UT", "UU", "UV", "UW", "UX", "UY", "UZ",
  // V
  "VA", "VB", "VC", "VD", "VE", "VF", "VG", "VH", "VJ", "VK", "VL", "VM", "VN", "VO", "VP", "VQ", "VR", "VS", "VT", "VU", "VV", "VW", "VX", "VY", "VZ",
  // W
  "WA", "WB", "WC", "WD", "WE", "WG", "WH", "WI", "WJ", "WK", "WP", "WQ", "WR", "WS", "WT", "WU", "WV", "WX", "WY", "WZ"
};

const int FAKE_KENNZEICHEN_COUNT = sizeof(FAKE_KENNZEICHEN) / sizeof(char*);

#endif
